#ifndef FIREDANCER_PROTO_GOOGLE_PROTOBUF_TIMESTAMP_PB_H
#define FIREDANCER_PROTO_GOOGLE_PROTOBUF_TIMESTAMP_PB_H

#include "../../timestamp.pb.h"

#endif /* FIREDANCER_PROTO_GOOGLE_PROTOBUF_TIMESTAMP_PB_H */
